### ISSUE TITLE
error prefetching hash: exit status 1

### ISSUE THREAD

**Issue by lilyball** [nixcloud/dep2nix#19]
I'm trying to use this on a project with a Gopkg.lock and when I run `dep2nix` I get the output

```
Found 22 projects to process.
* Processing: "[redacted]/common/golibs"
error prefetching hash: exit status 1
```

The project is an internal project but the import domain doesn't require authentication AFAICT (it just requires being on VPN, which I am). I don't know what "error prefetching hash" means. The Gopkg.lock file lists this for the given dependency:

```toml
[[projects]]
  digest = "1:8b59f86796b3cf384bde6c7b3ab2da9fa4c7eff057d216ccd420c80894a9c36f"
  name = "[redacted]/common/golibs"
  packages = [
    "bininfo",
    "pkgpath",
  ]
  pruneopts = "NUT"
  revision = "c3c7c6b379004afc72b5a25e220515c2da72d9e4"
```
