### ISSUE TITLE
Source declaration is ignored

### ISSUE THREAD

**Issue by CrushedPixel** [nixcloud/dep2nix#5]
My `Gopkg.toml` contains a `source` rule to overwrite the git repository from which a dependency should be fetched.
The corresponding `Gopkg.lock` entry looks like this:
```toml
[[projects]]
  branch = "master"
  name = "github.com/google/jsonapi"
  packages = ["."]
  revision = "ed520b3a37447a090eb36826364df8e06f3601d7"
  source = "https://github.com/CrushedPixel/jsonapi"
```
`dep2nix` ignores the lock file's `source` rule, generating the following entry in `deps.nix`:
```nix
    {
      goPackagePath  = "github.com/google/jsonapi";
      fetch = {
        type = "git";
        url = "https://github.com/google/jsonapi";
        rev =  "ed520b3a37447a090eb36826364df8e06f3601d7";
        sha256 = "00gl8j33mxbkh0wp064dgq74znai9gdm7kpp4vbhrya8q7zgxsf4";
      };
    }
```
